# Generated by Django 4.1.5 on 2023-01-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("krenger", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordcard",
            old_name="word",
            new_name="name",
        ),
    ]
